const json=(b,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hash(v){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)));}
function cookieValue(r,n){for(const p of (r.headers.get('Cookie')||'').split(';')){const [k,...v]=p.trim().split('=');if(k===n)return v.join('=')}return''}
async function auth(request,env){const t=cookieValue(request,'oneprofile_session');if(!t)return null;const h=await hash(t),now=Math.floor(Date.now()/1000);const s=await env.ONEPROFILE_DB.prepare('SELECT enrollment_id,expires_at FROM oneprofile_sessions WHERE token_hash=? LIMIT 1').bind(h).first();return s&&Number(s.expires_at)>=now?s:null}
const allowed=['preferred_name','communication_method','communication_notes','sensory_triggers','calming_supports','touch_preference','safety_risk_level','known_destinations','safe_approach','emergency_contact_name','emergency_contact_relationship','emergency_contact_phone','alternate_contact_name','alternate_contact_phone','responder_notes'];
function token(){const a=new Uint8Array(18);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export async function onRequestGet({request,env}){try{const a=await auth(request,env);if(!a)return json({authenticated:false},401);const p=await env.ONEPROFILE_DB.prepare('SELECT public_profile_enabled,public_token,public_fields FROM oneprofile_profiles WHERE enrollment_id=?').bind(a.enrollment_id).first();return json({authenticated:true,enabled:!!p?.public_profile_enabled,public_token:p?.public_token||'',fields:JSON.parse(p?.public_fields||'[]')})}catch(e){console.error(e);return json({error:'Unable to load sharing settings.'},500)}}
export async function onRequestPost({request,env}){try{const a=await auth(request,env);if(!a)return json({authenticated:false},401);const b=await request.json();const fields=[...new Set((Array.isArray(b.fields)?b.fields:[]).filter(x=>allowed.includes(x)))];const enabled=!!b.enabled;if(enabled&&!fields.length)return json({error:'Choose at least one item to share.'},400);let p=await env.ONEPROFILE_DB.prepare('SELECT public_token FROM oneprofile_profiles WHERE enrollment_id=?').bind(a.enrollment_id).first();let t=p?.public_token||token();await env.ONEPROFILE_DB.prepare(`UPDATE oneprofile_profiles SET public_profile_enabled=?,public_token=?,public_fields=?,public_enabled_at=CASE WHEN ?=1 THEN COALESCE(public_enabled_at,datetime('now')) ELSE public_enabled_at END,updated_at=datetime('now') WHERE enrollment_id=?`).bind(enabled?1:0,t,JSON.stringify(fields),enabled?1:0,a.enrollment_id).run();return json({ok:true,enabled,public_token:t,fields,url:`/emergency.html?id=${encodeURIComponent(t)}`})}catch(e){console.error(e);return json({error:'Unable to save sharing settings.'},500)}}
export async function onRequest(c){if(c.request.method==='GET')return onRequestGet(c);if(c.request.method==='POST')return onRequestPost(c);return json({error:'Method not allowed'},405)}
